
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugohngawkzymjvuwjqyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnb2huZ2F3a3p5bWp2dXdqcXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTc4MjIsImV4cCI6MjA2MDM3MzgyMn0.jyue1Jl21KvYQj_fz1CzchZSJFO5yDvFya27kwGbk6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Initialize storage bucket for question images if it doesn't exist
const createStorageBucket = async () => {
  try {
    const { data, error } = await supabase.storage.getBucket('question-images');
    if (error && error.message.includes('does not exist')) {
      await supabase.storage.createBucket('question-images', {
        public: true,
        fileSizeLimit: 2097152, // 2MB
      });
    }
  } catch (error) {
    console.error('Error checking/creating storage bucket:', error);
  }
};

// Run this once when the client initializes
createStorageBucket();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
